version: "3.8"
services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ozmapsync
    command: --default-authentication-plugin=mysql_native_password
    ports: [ "3306:3306" ]
    volumes: [ "mysql:/var/lib/mysql" ]

  redis:
    image: redis:7-alpine
    ports: [ "6379:6379" ]

  app:
    build: .
    env_file: .env
    depends_on: [ mysql, redis ]
    ports: [ "3000:3000" ]
    image: node:20-alpine
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

volumes:
  mysql: {}
